### ISSUE TITLE
[REQUEST] Cartridge Release 3D Mario Games decompilation into source code.

### ISSUE THREAD

**Issue by ghost** [n64decomp/sm64#10]
Super Mario 64 DS decompilation
Super Mario 3D Land decompilation
Super Mario Odyssey decompilation
Super Mario 3D World Deluxe decompilation

**Comment by chungy** [comment]
Someone on Hacker News[1] posted a list of reverse engineering projects similar to this

Sunshine: https://github.com/shibbo/Corona/blob/master/include/actor/TLiveActor.h
Galaxy: https://github.com/shibbo/Petari/blob/master/include/Actor/LiveActor/LiveActor.h
Odyssey: https://github.com/shibbo/OdysseyReversed/blob/master/include/al/LiveActor.h

[1] https://news.ycombinator.com/item?id=20804144

**Comment by ProjectRevoTPP** [comment]
The scope of this project pertains to Super Mario 64 only.

If you want to see other games decompiled I suggest you either Google or view those links above.
