### ISSUE TITLE
Build Error (US)

### ISSUE THREAD

**Issue by maiorano84** [n64decomp/sm64#11]
Just thought I'd give this a shot.

I feel like I'm pretty close in getting this to decompile, but I'm running into the following error during the build process:

```
/qemu-irix/irix-linux-user/qemu-irix -silent -L tools/ido5.3_compiler tools/ido5.3_compiler/usr/bin/cc -c -Wab,-r4300_mul -non_shared -G 0 -Xcpluscomm -Xfullwarn -g -signed -I include -I build/us/include -I src -D_LANGUAGE_C -DVERSION_US=1 -mips2 -32 -DF3D_OLD -o build/us/src/engine/surface_collision.o src/engine/surface_collision.c
cc: full_path: Invalid argument
make: *** [Makefile:430: build/us/src/engine/surface_collision.o] Error 1
```

**OS**: Debian (Latest) and Ubuntu (Latest)  
**Packages Installed**: `git build-essential zlib1g-dev pkg-config libglib2.0-dev binutils-dev libboost-all-dev autoconf libtool libssl-dev libpixman-1-dev libpython-dev python-pip python-capstone virtualenv flex bison binutils-mips-linux-gnu python3 libaudiofile-dev`  
**QEMU-Irix**: Compiled from [source](https://github.com/n64decomp/sm64) using `configure --target-list=irix-linux-user,irixn32-linux-user,irix64-linux-user,solaris-linux-user && make && make install`.
**Base ROM**: baserom.us.z64

Let me know if you need any more information.

**Comment by Velyphus** [comment]
Seems like a problem with your `qemu_irix`, I would suggest you get the binary from the releases tab on this repository.

**Comment by maiorano84** [comment]
Awesome. I'll give that a whirl tonight. I'm putting together a Docker container that can automate the decompiling process a little more and abstract some of the lower-level concepts away. I'll follow up with everything.

**Comment by maiorano84** [comment]
Sadly, still the same error.

Here's the list of Docker command instructions I'm using:

```
FROM debian:latest

RUN apt-get update && \
    apt-get install -y wget git binutils-mips-linux-gnu python3 \
    build-essential pkg-config zlib1g-dev libaudiofile-dev

RUN wget -O /usr/local/bin/qemu-irix https://github.com/n64decomp/sm64/releases/download/irix2/qemu-irix && \
    chmod +x /usr/local/bin/qemu-irix
ENV QEMU_IRIX=/usr/local/bin/qemu-irix

RUN git clone https://github.com/n64decomp/sm64.git

# Copy the baserom into the image
COPY baseroms/baserom.us.z64 /sm64/baserom.us.z64
WORKDIR /sm64
ENTRYPOINT ["make"]
```

Nothing here is standing out to me as particularly problematic, so I'm thinking that perhaps my own baserom might be somehow malformed or problematic in some way.

**Comment by chungy** [comment]
The baserom sha1 should be `9bef1128717f958171a4afac3ed78ee2bb4e86ce` for the US version.

**Comment by maiorano84** [comment]
@chungy The wording of the README led me to believe that sha1 was what we ended up with, not what we started with. But that makes sense since we're decompiling a ROM. Not ending up with one. I'll see what I can find.

**Comment by maiorano84** [comment]
Marking this issue as closed pending further investigation

**Comment by ToruTheRedFox** [comment]
might want to make sure that you have full permissions for the directory the decompilation is in

that was the problem for me

**Comment by v64** [comment]
I encountered this problem when trying to use a virtual machine to compile the source stored on an external USB drive. Copying the source from the external drive to the VM's disk fixed the problem. I tried to figure out why that fixed it, but didn't make any headway.
