### ISSUE TITLE
Fatal Build Error

### ISSUE THREAD

**Issue by zjfoede** [n64decomp/sm64#15]
When I attempt to compile I get a fatal error, complaining about a segmentation violation on dynlists_mario_eyebrows_mustache.c:

> /usr/bin/qemu-irix -silent -L tools/ido5.3_compiler tools/ido5.3_compiler/usr/bin/cc -c -Wab,-r4300_mul -non_shared -G 0 -Xcpluscomm -Xfullwarn -g -signed -I include -I build/us/include -I src -D_LANGUAGE_C -DVERSION_US=1 -mips1 -DF3D_OLD -o build/us/src/goddard/dynlists/dynlists_mario_eyebrows_mustache.o src/goddard/dynlists/dynlists_mario_eyebrows_mustache.c
cfe: Fatal: src/goddard/dynlists/dynlists_mario_eyebrows_mustache.c: Segmentation violation
make: *** [Makefile:434: build/us/src/goddard/dynlists/dynlists_mario_eyebrows_mustache.o] Error 1

OS: Manjaro, all packages are up to date.
qemu-irix: sourced from AUR. Also attempted using the version from the Releases tab with the same result.
Default make options.

**Comment by JoshDuMan** [comment]
Your file location needs to be less than 255 characters or something like that. Attempt putting the repo in a lower folder and building that.

**Comment by zjfoede** [comment]
That did it, thanks!
