### ISSUE TITLE
compiler works fine and then has a segmentation fault

### ISSUE THREAD

**Issue by davFaithid** [n64decomp/sm64#25]
It was working perfectly until it reached 
``
mips-linux-gnu-ld -e 0 -Ttext=0x07000000 -Map build/us/levels/wdw/leveldata.elf.map --just-symbols=build/us/bin/grass.elf -o build/us/levels/wdw/leveldata.elf build/us/levels/wdw/leveldata.o
Makefile:386: recipe for target 'build/us/levels/wdw/leveldata.elf' failed
make: *** [build/us/levels/wdw/leveldata.elf] Segmentation fault (core dumped)
make: *** Deleting file 'build/us/levels/wdw/leveldata.elf'
``
and then it goes into a large `rm` command.
Now, I do not know much about what a "segmentation fault" is, but I highly doubt it was supposed to happen. Any idea on how to fix this issue?
I am on Windows 10 using WSL
Thank you.

**Comment by CrashOveride95** [comment]
Where did you put the decomp folder?

**Comment by farisawan-2000** [comment]
Check if your path is too long or would be too long with the addition of the repo (it usually adds like 50-75 characters to your path, where the overall limit is 255).

Usually directories like  /home/<user>/sm64 and /mnt/c/sm64 are good sizes

**Comment by davFaithid** [comment]
@farisawan-2000 thank you very much for your answer. It fixed the segmentation fault error, but now I have another.

``
build/us/src/game/room.o:(.bss+0x0): multiple definition of `gCheckingSurfaceCollisionsForCamera'
build/us/src/game/object_list_processor.o:src/game/object_list_processor.c:687: first defined here
build/us/src/game/room.o:(.bss+0x2): multiple definition of `gFindFloorIncludeSurfaceIntangible'
build/us/src/game/object_list_processor.o:src/game/object_list_processor.c:687: first defined here
build/us/src/game/room.o:(.bss+0x4): multiple definition of `gEnvironmentRegions'
build/us/src/game/object_list_processor.o:src/game/object_list_processor.c:687: first defined here
build/us/src/game/room.o:(.bss+0x8): multiple definition of `gEnvironmentLevels'
build/us/src/game/object_list_processor.o:src/game/object_list_processor.c:687: first defined here
build/us/src/game/room.o:(.bss+0x58): multiple definition of `gDoorAdjacentRooms'
build/us/src/game/object_list_processor.o:src/game/object_list_processor.c:687: first defined here
build/us/src/game/room.o:(.bss+0xd0): multiple definition of `gMarioCurrentRoom'
build/us/src/game/object_list_processor.o:src/game/object_list_processor.c:687: first defined here
build/us/src/game/room.o:(.bss+0xd2): multiple definition of `D_8035FEE2'
build/us/src/game/object_list_processor.o:src/game/object_list_processor.c:687: first defined here
build/us/src/game/room.o:(.bss+0xd4): multiple definition of `D_8035FEE4'
build/us/src/game/object_list_processor.o:src/game/object_list_processor.c:687: first defined here
build/us/src/game/room.o:(.bss+0xd6): multiple definition of `gTHIWaterDrained'
build/us/src/game/object_list_processor.o:src/game/object_list_processor.c:687: first defined here
build/us/src/game/room.o:(.bss+0xd8): multiple definition of `gTTCSpeedSetting'
build/us/src/game/object_list_processor.o:src/game/object_list_processor.c:687: first defined here
build/us/src/game/room.o:(.bss+0xda): multiple definition of `gMarioShotFromCannon'
build/us/src/game/object_list_processor.o:src/game/object_list_processor.c:687: first defined here
build/us/src/game/room.o:(.bss+0xdc): multiple definition of `gCCMEnteredSlide'
build/us/src/game/object_list_processor.o:src/game/object_list_processor.c:687: first defined here
build/us/src/game/room.o:(.bss+0xde): multiple definition of `gNumRoomedObjectsInMarioRoom'
build/us/src/game/object_list_processor.o:src/game/object_list_processor.c:687: first defined here
build/us/src/game/room.o:(.bss+0xe0): multiple definition of `gNumRoomedObjectsNotInMarioRoom'
build/us/src/game/object_list_processor.o:src/game/object_list_processor.c:687: first defined here
build/us/src/game/room.o:(.bss+0xe2): multiple definition of `gWDWWaterLevelChanging'
build/us/src/game/object_list_processor.o:src/game/object_list_processor.c:687: first defined here
build/us/src/game/room.o:(.bss+0xe4): multiple definition of `gMarioOnMerryGoRound'
build/us/src/game/object_list_processor.o:src/game/object_list_processor.c:687: first defined here
Makefile:515: recipe for target 'build/us/sm64.us.elf' failed
make: *** [build/us/sm64.us.elf] Error 1
``
I think I should probably put this as a separate error though
