### ISSUE TITLE
Build Error audiofile.h

### ISSUE THREAD

**Issue by Primkinkajou** [n64decomp/sm64#32]
When attempting to decompile the project I run into this error:

`sdk-tools/tabledesign/tabledesign.c:5:23: fatal error: audiofile.h: No such file or directory
compilation terminated.
Makefile:49: recipe for target 'tabledesign' failed
make: *** [tabledesign] Error 1
Makefile:123: *** Failed to build tools.  Stop.`

I redownloaded all of the files to make sure I'm not missing any, but the error still persists. Any ideas on what I'm doing wrong?

**Comment by ProjectRevoTPP** [comment]
libaudiofile-dev

**Comment by Primkinkajou** [comment]
Thanks for your quick reply, but what does that mean?

**Comment by nim-ka** [comment]
You failed to follow the instructions. Please read the README again, specifically where it says which packages to install.

If you require further assistance, please join our discord server and see our FAQ there, which should solve all your common issues.
