### ISSUE TITLE
About replacing the 3D models

### ISSUE THREAD

**Issue by Cloudef** [n64decomp/sm64#38]
Do you happen to have or know tools for replacing the 3D model data / levels in the source code? Maybe blender export plugin. I'm aware of tools for editing the models / levels in the rom itself, those tools are awfully windows specific though.

**Comment by farisawan-2000** [comment]
https://bitbucket.org/kurethedead/fast64

this is the main plugin, compatible with Blender.

**Comment by Cloudef** [comment]
That was a amazingly fast reply. Thanks!
