### ISSUE TITLE
Illegal repo

### ISSUE THREAD

**Issue by IAmRudeAndDelusional** [n64decomp/sm64#4]
I have reported this to the GitHub admins. Hope Nintendo sues your ass into oblivion. You should be ashamed of yourself for releasing this.

**Comment by Clark-E** [comment]
If I understand this correctly, this isn’t the original source code. They decompiled the rom file, cleaned up and annotated it, and posted it here. So, not illegal, I’m guessing.

**Comment by TastyUdders** [comment]
Your name makes sense.

**Comment by brushtool** [comment]
is this supersmeg64 or whoever he was called

**Comment by atasro2** [comment]
Maybe you should study some laws and then come here making accusations because this repo doesn't violate any law that i know of unless some lawyer pulls off a nasty trick

**Comment by CrashOveride95** [comment]
Didn't you already spam reddit comment sections about this repo with this reactionary tripe? calm down and take a chill pill man, I'd like to see the exact rule violation you speak of, *if any*

**Comment by ITotalJustice** [comment]
Obvious troll, name should give it away. Account also created 2 hours ago and this is their first issue.

**Comment by koutsie** [comment]
im just curious why...
why would someone do this.

also not even a good troll, cmon man.

**Comment by GlitchyPSIX** [comment]
You've gotta have dangerous levels of salt to pull something like this
